### PR TITLE
Added 3d printable enclosure

### PR DESCRIPTION
**Pull request by fabriziofiorucci**
Added stl files and images for a 3d printable enclosure

### CODE REVIEW

**Comment by sweetlilmre** [comment]
Hi,

I fixed up the readme a bit. Also wanted to let you know I printed the connector part (but cut off the logo so it would print the top flat without supports, and it's brilliant! What a great fit!)

**Comment by fabriziofiorucci** [comment]
Thank you, glad it worked!

**Comment by sweetlilmre** [comment]
Merged and thank you!

**Comment by fabriziofiorucci** [comment]
Thanks!

**Pull request merged**
