### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by matsstaff**
Hi!

First off, many thanks for Tapuino!

I've been tweaking the code for my own needs and stumbled on some things. First off, SRAM usage is high. While I guess by now it is proven that Tapuino works ok, more free SRAM is always good. Most of the usage comes from FatFs buffers and can't really improve, but I found a 128 byte Look Up Table that could move to program space, giving the stack some more room.
Secondly, I found a minor bug, that I think happens to work (at least most of the time), but should be corrected.

I'm sorry that I don't have a Tapuino development setup right now to actually test the changes (and I might have messed up). I hope to have a dev-setup going soon and hope to submit better tested pull-requests in the future (if you want them).

Cheers!
//mats

### CODE REVIEW

**Comment by sweetlilmre** [comment]
Hi,

Thank you for the pull request. As you can tell I have been busy with life and not looked into this repo for a long time so apologies for not getting back to you. I am not sure if you are still interested, but here are my comments:

- The LUT to PGM space change is great, thank you.
- I don't feel the g_tap_info refactor is worth it in terms of space saved versus ease of use / readability
- the unchecked br variable is a good catch, I just found out where this error crept in from a refactor.
- removing the g_key_repeat_start from the eprom load/store routines will corrupt previous settings, so this would require that a zero value be written in it's place. In terms of this, leaving it as is for future expansion or re-use is a better option IMHO.
- The TAP ISR refactor is significant and will take some time to look at.
- The change in the code of the ISR to move tap_data from a uint32_t  to uint16_t datatype is problematic in that tap values can be up to 24 bits wide (long pulse).

I will pull some of the smaller changed into my tree and apply them, then consider the refactor.
Thank you again for your submission.

**Comment by matsstaff** [comment]
Hi!
No worries, thanks for the response :)
It's been a while since I was messing about with Tapuino (or retrocomputing at all) as well, so I don't remember all that much....
The ISR stuff was mainly a refactor, to avoid duplicated code as I recall. I might have been mistaken to change the size of tap_data. Feel free to use or reject what you want.
I've had some great fun with Tapuino, it is a really neat project!
Thank you again for your work and for making it free (as in freedom)! 
//mats

**Comment by sweetlilmre** [comment]
Hey Mats,

I've cherry picked some of the changes and as soon as I can find my programmer, I'll test them.

Thank you again for your efforts and if you ever get back into needing a Tapuino, check out the new version at: https://github.com/sweetlilmre/TapuinoNext

**Comment by sweetlilmre** [comment]
Hey Mats,

Just some further updates. I merged your memory optimizations into the code, tested and released a new version (thank you again!).

I then pulled in the ISR refactor. It wasn't quite correct, but didn't take too much to fix it (in short there was an issue with reading a value from the TAP file for the 2nd half of the wave form, when this should only be done for v2 formats). At any rate I've reworked that in the refactor branch along with some other optimizations and code that is a little safer and am testing it now. The good news is it seems to work and makes the code cleaner, so much appreciated. The XOR trick with the invert / 2nd half flags was inspired!

**Pull request closed without merging**
